apiVersion: v1
kind: Namespace
metadata:
  name: kube-notify-plus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-inspector
  namespace: kube-notify-plus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-inspector-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-inspector-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: pod-inspector
  namespace: kube-notify-plus
roleRef:
  kind: ClusterRole
  name: pod-inspector-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: pod-inspector-token
  namespace: kube-notify-plus
  annotations:
    kubernetes.io/service-account.name: pod-inspector
type: kubernetes.io/service-account-token
