apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-error-example
  labels:
    app: configmap-error
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmap-error
  template:
    metadata:
      labels:
        app: configmap-error
    spec:
      containers:
      - name: configmap-error-example
        image: busybox
        command: ["sh", "-c", "cat /config/config-file"]
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: non-existent-configmap