apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-throttle-example
  labels:
    app: cpu-throttle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-throttle
  template:
    metadata:
      labels:
        app: cpu-throttle
    spec:
      containers:
      - name: cpu-throttle-example
        image: containerstack/cpustress
        args: ["--cpu", "2", "--timeout", "30s"]
        resources:
          limits:
            cpu: "100m"
          requests:
            cpu: "50m"
