apiVersion: apps/v1
kind: Deployment
metadata:
  name: oom-example
  labels:
    app: oom-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oom-example
  template:
    metadata:
      labels:
        app: oom-example
    spec:
      containers:
      - name: oom-example
        image: polinux/stress
        command: ["stress", "--vm", "1", "--vm-bytes", "128M", "--timeout", "30s"]
        resources:
          limits:
            memory: "64Mi"
          requests:
            memory: "64Mi"