apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-failure-example
  labels:
    app: probe-failure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probe-failure
  template:
    metadata:
      labels:
        app: probe-failure
    spec:
      containers:
      - name: probe-failure-example
        image: nginx
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /non-existent-path
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /non-existent-path
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
