apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-error-example
  labels:
    app: secret-error
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-error
  template:
    metadata:
      labels:
        app: secret-error
    spec:
      containers:
      - name: secret-error-example
        image: busybox
        command: ["sh", "-c", "cat /secrets/secret-file"]
        volumeMounts:
        - name: secret-volume
          mountPath: /secrets
      volumes:
      - name: secret-volume
        secret:
          secretName: non-existent-secret
